name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build -vv --all --release
    - name: Run tests
      run: cargo test -vv --all --release
    - name: run
      run: cargo run > output.ppm
    - uses: actions/upload-artifact@v2
      with:
        name: output.ppm
        path: output.ppm

