name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: cargo build -v --all
    - run: cargo test -v --all
    - run: cargo test -v --all --release
    - name: test output
      run: |
        cargo run --release > test-output.ppm
        diff output.ppm test-output.ppm
    - uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: test-output.ppm

