name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build -v --all
      timeout-minutes: 3
    - name: Run tests
      run: cargo test -v --all
      timeout-minutes: 3
    - name: Run tests
      run: cargo test -v --all --release
      timeout-minutes: 3
    - name: run
      run: cargo run --release > output.ppm
      timeout-minutes: 3
    - uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: output.ppm

